### ISSUE TITLE
uploading to arxiv

### ISSUE THREAD

**Issue by afeinstein20** [afeinstein20/v1298tau_tess#3]
hey @rodluger For some reason, the tarball downloaded directly from `showyourwork` is struggling to interact with arxiv. Although the PDF compiles just fine, and all references/figures are linked properly, I'm getting the following warnings:

- `Package natbib Warning: Citation 'reference' on page [m] undefined on input line [n]`
- `LaTeX Warning: Reference 'sec:conclusions' on page [m] undefined on input line [n]`
- `LaTeX Warning: Reference 'fig:' on page [m] undefined on input line [n]`

And as such, even though the compiled PDF looks fine, arxiv keeps halting my submission. Any advice?

**Comment by rodluger** [comment]
Weird. I'd be surprised if those warnings were the issue -- are you sure there isn't an error buried deep in the logs? Let me try to upload it myself and see what happens -- I'll get back to you shortly.

**Comment by afeinstein20** [comment]
Here's the email I got from arxiv tech support!

> Dear arXiv user,
> 
> Many of the references in your paper are undefined. This condition can be caused by several cases, such as using multiple .bib files to generate a .bbl, but doing so incompletely, or via interactions between hyperref and cleverref. Please refer to the bibtex help documentation if you used used multiple bib files. arXiv's copy of hyperref and cleverref does not always produce the desired output, Please include your local copy of the cleverref.sty and hyperref.sty. Please also remove any .synctex and .out files, as they are not needed, if present.
> 
> Regards,
> The arXiv User Support Team

**Comment by rodluger** [comment]
Strange! So you can actually go through with the submission to the end, but then you get an email from arXiv saying it didn't work? All the refs look fine in the PDF I uploaded to arXiv, except for the numpy one:

![image](https://user-images.githubusercontent.com/9323819/142026503-0cae77a1-0f46-457b-bebc-e7784e0b21b8.png)

**Comment by rodluger** [comment]
Yeah this looks fishy: https://github.com/afeinstein20/v1298tau_tess/blob/main/src/main.bib#L1073

**Comment by rodluger** [comment]
Looks like ``\citep{Feinstein21}`` defined [here](https://github.com/afeinstein20/v1298tau_tess/blob/main/src/ms.tex#L65) is also undefined. Hence "many" :)

**Comment by afeinstein20** [comment]
I agree that the `numpy` reference was sketchy... Not sure why since I took my .bib from Overleaf 😅 but `\citep{Feinstein21}` is definitely in there... Hmm I'll keep digging around for those undefined ones. Thanks!!

**Comment by rodluger** [comment]
Oh it must be the `johnson21` one then, on the same line.

![image](https://user-images.githubusercontent.com/9323819/142028365-085c698c-f83f-4168-8e73-13121a71dab7.png)

**Comment by afeinstein20** [comment]
Oop, yes that fixed everything! sorry about that 😅 and thanks for your help!!
