### ISSUE TITLE
Upgrade to showyourwork v0.2.0

### ISSUE THREAD

**Issue by rodluger** [afeinstein20/v1298tau_tess#4]
Hey @afeinstein20, run a 

```
make update
```

and commit & push your changes to GitHub when you get a chance. Among the many changes is a switch to installing `snakemake-minimal` instead of `snakemake`. Something in either `mamba` or one of the dependencies of `snakemake` changed in the past ~month, causing the `conda` installation to just hang. The update should fix the errors you're getting on CI.

**Comment by afeinstein20** [comment]
heck yeah, that worked. thanks!
