### ISSUE TITLE
Showcase this paper on the showyourwork docs?

### ISSUE THREAD

**Issue by rodluger** [afeinstein20/v1298tau_tess#5]
Hey @afeinstein20, would you be interested in showcasing this paper on the [showyourwork documentation](https://showyourwork.readthedocs.io/en/stable/projects/)? It's just a matter of entering the metadata in [this JSON file](https://github.com/rodluger/showyourwork/blob/main/docs/projects.json) via a PR.

**Comment by afeinstein20** [comment]
Oh, this is sweet! I will definitely enter our info here. Thanks!!
